<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Şebnem Er">

<title>Applied Spatial Data Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#spatial-point-pattern" id="toc-spatial-point-pattern" class="nav-link active" data-scroll-target="#spatial-point-pattern">Spatial Point Pattern</a>
  <ul class="collapse">
  <li><a href="#background-definition" id="toc-background-definition" class="nav-link" data-scroll-target="#background-definition">Background, Definition</a></li>
  <li><a href="#r-packages-necessary" id="toc-r-packages-necessary" class="nav-link" data-scroll-target="#r-packages-necessary">R Packages necessary</a></li>
  <li><a href="#application-areas" id="toc-application-areas" class="nav-link" data-scroll-target="#application-areas">Application Areas</a>
  <ul class="collapse">
  <li><a href="#example-1-trees" id="toc-example-1-trees" class="nav-link" data-scroll-target="#example-1-trees">Example 1: Trees</a></li>
  <li><a href="#example-2-cholera" id="toc-example-2-cholera" class="nav-link" data-scroll-target="#example-2-cholera">Example 2: Cholera</a></li>
  <li><a href="#example-3-stars-ara-constellation" id="toc-example-3-stars-ara-constellation" class="nav-link" data-scroll-target="#example-3-stars-ara-constellation">Example 3: Stars – Ara Constellation</a></li>
  <li><a href="#example-4-clinics" id="toc-example-4-clinics" class="nav-link" data-scroll-target="#example-4-clinics">Example 4: Clinics</a></li>
  <li><a href="#example-5-fluorspar" id="toc-example-5-fluorspar" class="nav-link" data-scroll-target="#example-5-fluorspar">Example 5: Fluorspar</a></li>
  <li><a href="#example-6-public-electricity-lighting---from-.shp-file" id="toc-example-6-public-electricity-lighting---from-.shp-file" class="nav-link" data-scroll-target="#example-6-public-electricity-lighting---from-.shp-file">Example 6: Public Electricity Lighting - from .shp file</a></li>
  <li><a href="#example-7-on-street-parking" id="toc-example-7-on-street-parking" class="nav-link" data-scroll-target="#example-7-on-street-parking">Example 7: On Street Parking</a></li>
  <li><a href="#data-resources-for-spp-for-cape-town-municipality" id="toc-data-resources-for-spp-for-cape-town-municipality" class="nav-link" data-scroll-target="#data-resources-for-spp-for-cape-town-municipality">Data Resources for SPP for Cape Town Municipality</a></li>
  <li><a href="#what-is-common-in-all-these-examples" id="toc-what-is-common-in-all-these-examples" class="nav-link" data-scroll-target="#what-is-common-in-all-these-examples">What is common in all these examples?</a></li>
  </ul></li>
  <li><a href="#spatial-point-pattern-types" id="toc-spatial-point-pattern-types" class="nav-link" data-scroll-target="#spatial-point-pattern-types">Spatial point pattern types</a>
  <ul class="collapse">
  <li><a href="#marked-point-patterns" id="toc-marked-point-patterns" class="nav-link" data-scroll-target="#marked-point-patterns">Marked point patterns</a></li>
  <li><a href="#key-terminology" id="toc-key-terminology" class="nav-link" data-scroll-target="#key-terminology">Key terminology</a></li>
  </ul></li>
  <li><a href="#key-terminology-1" id="toc-key-terminology-1" class="nav-link" data-scroll-target="#key-terminology-1">Key Terminology</a>
  <ul class="collapse">
  <li><a href="#displaced-amacrine-cells-in-the-retina-of-a-rabbit-analysis-of-a-bivariate-spatial-point-pattern-by-peter-j.-diggle-1986" id="toc-displaced-amacrine-cells-in-the-retina-of-a-rabbit-analysis-of-a-bivariate-spatial-point-pattern-by-peter-j.-diggle-1986" class="nav-link" data-scroll-target="#displaced-amacrine-cells-in-the-retina-of-a-rabbit-analysis-of-a-bivariate-spatial-point-pattern-by-peter-j.-diggle-1986">Displaced amacrine cells in the retina of a rabbit: analysis of a bivariate spatial point pattern by Peter J. Diggle (1986)</a></li>
  </ul></li>
  <li><a href="#spatial-point-pattern-types-g-point-networks" id="toc-spatial-point-pattern-types-g-point-networks" class="nav-link" data-scroll-target="#spatial-point-pattern-types-g-point-networks">Spatial Point Pattern Types – (g) Point Networks</a></li>
  <li><a href="#what-is-the-research-question-here" id="toc-what-is-the-research-question-here" class="nav-link" data-scroll-target="#what-is-the-research-question-here">What is the research question here?</a></li>
  </ul></li>
  <li><a href="#univariate-point-patterns" id="toc-univariate-point-patterns" class="nav-link" data-scroll-target="#univariate-point-patterns">Univariate point patterns</a>
  <ul class="collapse">
  <li><a href="#exploratory-analysis---intensity" id="toc-exploratory-analysis---intensity" class="nav-link" data-scroll-target="#exploratory-analysis---intensity">Exploratory analysis - Intensity</a></li>
  <li><a href="#intensity---homogeneous" id="toc-intensity---homogeneous" class="nav-link" data-scroll-target="#intensity---homogeneous">Intensity - Homogeneous</a></li>
  <li><a href="#intensity---inhomogeneous" id="toc-intensity---inhomogeneous" class="nav-link" data-scroll-target="#intensity---inhomogeneous">Intensity - Inhomogeneous</a></li>
  <li><a href="#intensity" id="toc-intensity" class="nav-link" data-scroll-target="#intensity">Intensity</a>
  <ul class="collapse">
  <li><a href="#units-of-intensity" id="toc-units-of-intensity" class="nav-link" data-scroll-target="#units-of-intensity">Units of Intensity</a></li>
  <li><a href="#defining-the-observation-window" id="toc-defining-the-observation-window" class="nav-link" data-scroll-target="#defining-the-observation-window">Defining the Observation Window</a></li>
  </ul></li>
  <li><a href="#intensity-example-1-swedishpines-data-bounding-box-rectangular" id="toc-intensity-example-1-swedishpines-data-bounding-box-rectangular" class="nav-link" data-scroll-target="#intensity-example-1-swedishpines-data-bounding-box-rectangular">Intensity Example 1: swedishpines data – Bounding Box (Rectangular)</a></li>
  <li><a href="#intensity-example-2-clinics-in-ct-2016---bounding-polygon-irregular" id="toc-intensity-example-2-clinics-in-ct-2016---bounding-polygon-irregular" class="nav-link" data-scroll-target="#intensity-example-2-clinics-in-ct-2016---bounding-polygon-irregular">Intensity Example 2: clinics in CT 2016 - Bounding Polygon (Irregular )</a>
  <ul class="collapse">
  <li><a href="#intensity-under-different-polygons-and-bounding-box-measures" id="toc-intensity-under-different-polygons-and-bounding-box-measures" class="nav-link" data-scroll-target="#intensity-under-different-polygons-and-bounding-box-measures">Intensity under different polygons and bounding box measures</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#properties-of-csr" id="toc-properties-of-csr" class="nav-link" data-scroll-target="#properties-of-csr">Properties of CSR</a>
  <ul class="collapse">
  <li><a href="#complete-spatial-randomness-homogeneous-poisson-process-regularity-and-clustering" id="toc-complete-spatial-randomness-homogeneous-poisson-process-regularity-and-clustering" class="nav-link" data-scroll-target="#complete-spatial-randomness-homogeneous-poisson-process-regularity-and-clustering">Complete Spatial Randomness (homogeneous Poisson process), Regularity and Clustering</a>
  <ul class="collapse">
  <li><a href="#complete-spatial-randomness-homogeneous-poisson-process" id="toc-complete-spatial-randomness-homogeneous-poisson-process" class="nav-link" data-scroll-target="#complete-spatial-randomness-homogeneous-poisson-process">Complete Spatial Randomness (homogeneous Poisson process)</a></li>
  </ul></li>
  <li><a href="#complete-spatial-randomness-csr" id="toc-complete-spatial-randomness-csr" class="nav-link" data-scroll-target="#complete-spatial-randomness-csr">Complete Spatial Randomness (CSR)</a></li>
  <li><a href="#methods-for-assessing-csr" id="toc-methods-for-assessing-csr" class="nav-link" data-scroll-target="#methods-for-assessing-csr">Methods for Assessing CSR</a>
  <ul class="collapse">
  <li><a href="#first-order-methods" id="toc-first-order-methods" class="nav-link" data-scroll-target="#first-order-methods">First-order methods</a></li>
  <li><a href="#distance-based-methods" id="toc-distance-based-methods" class="nav-link" data-scroll-target="#distance-based-methods">Distance-based methods</a></li>
  <li><a href="#second-order-methods" id="toc-second-order-methods" class="nav-link" data-scroll-target="#second-order-methods">Second-order methods</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#quadrat-counting-and-tests" id="toc-quadrat-counting-and-tests" class="nav-link" data-scroll-target="#quadrat-counting-and-tests">Quadrat Counting and Tests</a>
  <ul class="collapse">
  <li><a href="#quadrat-counting---poisson-process" id="toc-quadrat-counting---poisson-process" class="nav-link" data-scroll-target="#quadrat-counting---poisson-process">Quadrat Counting - Poisson Process</a></li>
  <li><a href="#quadrat-count-analysis" id="toc-quadrat-count-analysis" class="nav-link" data-scroll-target="#quadrat-count-analysis">Quadrat Count Analysis</a>
  <ul class="collapse">
  <li><a href="#example-simulated-csr-data" id="toc-example-simulated-csr-data" class="nav-link" data-scroll-target="#example-simulated-csr-data">Example – Simulated CSR Data</a></li>
  <li><a href="#quadrat-counts" id="toc-quadrat-counts" class="nav-link" data-scroll-target="#quadrat-counts">Quadrat counts</a></li>
  </ul></li>
  <li><a href="#comparing-observed-and-expected-quadrat-counts" id="toc-comparing-observed-and-expected-quadrat-counts" class="nav-link" data-scroll-target="#comparing-observed-and-expected-quadrat-counts">Comparing observed and expected quadrat counts</a>
  <ul class="collapse">
  <li><a href="#observed-and-expected-proportions" id="toc-observed-and-expected-proportions" class="nav-link" data-scroll-target="#observed-and-expected-proportions">Observed and expected proportions</a></li>
  <li><a href="#graphical-comparison" id="toc-graphical-comparison" class="nav-link" data-scroll-target="#graphical-comparison">Graphical comparison</a></li>
  <li><a href="#example-calculation" id="toc-example-calculation" class="nav-link" data-scroll-target="#example-calculation">Example calculation</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#quadrat-counting---chi-square-test" id="toc-quadrat-counting---chi-square-test" class="nav-link" data-scroll-target="#quadrat-counting---chi-square-test">Quadrat Counting - Chi-Square Test</a>
  <ul class="collapse">
  <li><a href="#quadrat-counting-observed-point-counts-n_j" id="toc-quadrat-counting-observed-point-counts-n_j" class="nav-link" data-scroll-target="#quadrat-counting-observed-point-counts-n_j">Quadrat counting – Observed point counts (<span class="math inline">\(n_j\)</span>)</a></li>
  <li><a href="#quadrat-counting-expected-point-counts-e_j" id="toc-quadrat-counting-expected-point-counts-e_j" class="nav-link" data-scroll-target="#quadrat-counting-expected-point-counts-e_j">Quadrat counting – Expected point counts (<span class="math inline">\(e_j\)</span>)</a></li>
  <li><a href="#quadrat-counting-expected-point-counts-e_j-in-r" id="toc-quadrat-counting-expected-point-counts-e_j-in-r" class="nav-link" data-scroll-target="#quadrat-counting-expected-point-counts-e_j-in-r">Quadrat counting – Expected point counts (<span class="math inline">\(e_j\)</span>) in R</a></li>
  <li><a href="#some-issues-with-quadrat-methods" id="toc-some-issues-with-quadrat-methods" class="nav-link" data-scroll-target="#some-issues-with-quadrat-methods">Some issues with Quadrat Methods</a></li>
  <li><a href="#global-vs-local-measures" id="toc-global-vs-local-measures" class="nav-link" data-scroll-target="#global-vs-local-measures">Global vs Local Measures</a></li>
  </ul></li>
  <li><a href="#inhomogeneous-poisson-process-ipp" id="toc-inhomogeneous-poisson-process-ipp" class="nav-link" data-scroll-target="#inhomogeneous-poisson-process-ipp">Inhomogeneous Poisson Process (IPP)</a>
  <ul class="collapse">
  <li><a href="#estimation-of-intensity-for-ipp" id="toc-estimation-of-intensity-for-ipp" class="nav-link" data-scroll-target="#estimation-of-intensity-for-ipp">Estimation of Intensity for IPP</a></li>
  <li><a href="#estimating-the-intensity-of-an-ipp-kernel-smoothing" id="toc-estimating-the-intensity-of-an-ipp-kernel-smoothing" class="nav-link" data-scroll-target="#estimating-the-intensity-of-an-ipp-kernel-smoothing">Estimating the Intensity of an IPP: Kernel Smoothing</a>
  <ul class="collapse">
  <li><a href="#border-correction" id="toc-border-correction" class="nav-link" data-scroll-target="#border-correction">Border correction</a></li>
  <li><a href="#kernel-density-for-csr-with-different-bandwidths" id="toc-kernel-density-for-csr-with-different-bandwidths" class="nav-link" data-scroll-target="#kernel-density-for-csr-with-different-bandwidths">Kernel Density for CSR with different Bandwidths</a></li>
  </ul></li>
  <li><a href="#kernel-density-in-existence-of-a-covariate" id="toc-kernel-density-in-existence-of-a-covariate" class="nav-link" data-scroll-target="#kernel-density-in-existence-of-a-covariate">Kernel density in existence of a covariate</a>
  <ul class="collapse">
  <li><a href="#kernel-density-in-existence-of-a-covariate-1" id="toc-kernel-density-in-existence-of-a-covariate-1" class="nav-link" data-scroll-target="#kernel-density-in-existence-of-a-covariate-1">Kernel density in existence of a covariate</a></li>
  </ul></li>
  <li><a href="#spatial-covariates" id="toc-spatial-covariates" class="nav-link" data-scroll-target="#spatial-covariates">Spatial Covariates</a>
  <ul class="collapse">
  <li><a href="#example-data-bei" id="toc-example-data-bei" class="nav-link" data-scroll-target="#example-data-bei">Example data: “bei”</a></li>
  </ul></li>
  <li><a href="#investigating-the-effect-of-a-spatial-covariate" id="toc-investigating-the-effect-of-a-spatial-covariate" class="nav-link" data-scroll-target="#investigating-the-effect-of-a-spatial-covariate">Investigating the Effect of a Spatial Covariate</a>
  <ul class="collapse">
  <li><a href="#quadrat-counting-based-on-a-covariate" id="toc-quadrat-counting-based-on-a-covariate" class="nav-link" data-scroll-target="#quadrat-counting-based-on-a-covariate">Quadrat Counting Based on a Covariate</a></li>
  <li><a href="#tropical-rain-forest-trees-dataset" id="toc-tropical-rain-forest-trees-dataset" class="nav-link" data-scroll-target="#tropical-rain-forest-trees-dataset">Tropical rain forest trees dataset</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="chapter2.slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li><li><a href="chapter2.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Applied Spatial Data Analysis</h1>
<p class="subtitle lead">Chapter 2 - Examples and Intensity</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Dr.&nbsp;Şebnem Er </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Department of Statistical Sciences, University of Cape Town
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<!--

format:
  pdf:
    code-overflow: wrap





---
format:
  revealjs:
    slide-number: true
    code-overflow: wrap
    chalkboard: true
execute:
  echo: true
  warning: false
  message: false
---






-->
<div style="page-break-after: always;"></div>
<section id="spatial-point-pattern" class="level1">
<h1>Spatial Point Pattern</h1>
<p>Background, Definition, Application Areas and SPP Data Types</p>
<hr>
<section id="background-definition" class="level2">
<h2 class="anchored" data-anchor-id="background-definition">Background, Definition</h2>
<ul>
<li>A ‘spatial point process’ is a stochastic process in which we observe spatial locations of some things or events of interest within a bounded region A.</li>
<li>The locations of the events generated by a point process in the area of study A will be called a point pattern.</li>
<li>The spatial arrangement of points is the main focus of investigation.</li>
</ul>
<p><img src="slide1.jpg" class="img-fluid" style="float:right;;width:100.0%"></p>
<p>Ref: [3] page 3. Figure 1.1</p>
</section>
<section id="r-packages-necessary" class="level2">
<h2 class="anchored" data-anchor-id="r-packages-necessary">R Packages necessary</h2>
<div class="cell" data-code-annotations="hover">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># Core spatial data handling and maps</span></span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="fu">library</span>(terra)</span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="fu">library</span>(tmap)</span>
<span id="cb1-5"><a href="#cb1-5"></a><span class="fu">library</span>(leaflet)</span>
<span id="cb1-6"><a href="#cb1-6"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-7"><a href="#cb1-7"></a></span>
<span id="cb1-8"><a href="#cb1-8"></a><span class="co"># Spatial dependence and spatial regression</span></span>
<span id="cb1-9"><a href="#cb1-9"></a><span class="fu">library</span>(spdep)</span>
<span id="cb1-10"><a href="#cb1-10"></a><span class="fu">library</span>(spatialreg)</span>
<span id="cb1-11"><a href="#cb1-11"></a></span>
<span id="cb1-12"><a href="#cb1-12"></a><span class="co"># Spatial point patterns</span></span>
<span id="cb1-13"><a href="#cb1-13"></a><span class="fu">library</span>(spatstat.geom)</span>
<span id="cb1-14"><a href="#cb1-14"></a><span class="fu">library</span>(spatstat.explore)</span>
<span id="cb1-15"><a href="#cb1-15"></a><span class="fu">library</span>(spatstat.model)</span>
<span id="cb1-16"><a href="#cb1-16"></a><span class="fu">library</span>(deldir)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="application-areas" class="level2">
<h2 class="anchored" data-anchor-id="application-areas">Application Areas</h2>
<p>Examples include:</p>
<ul>
<li>the locations of trees in a forest, the spatial distribution of the trees, competition or coordination between different species of vegetation</li>
<li>gold deposits mapped in a geological survey,</li>
<li>stars in a star cluster,</li>
<li>road accidents,</li>
<li>earthquake epicentres,</li>
<li>mobile phone calls,</li>
<li>facility locations,</li>
<li>animal sightings,</li>
<li>cases of a rare disease, are they clustered, reasons why,</li>
<li><a href="https://michaelhoweely.com/2020/07/20/visualizing-crime-in-south-africa-data/">place where crime occurs</a> – <a href="https://issafrica.org/iss-today/better-police-use-of-data-could-cut-south-africas-crime">hotspots (we need good data for this:</a> <a href="https://www.crimestatssa.com/">check out:</a></li>
</ul>
<hr>
<section id="example-1-trees" class="level3">
<h3 class="anchored" data-anchor-id="example-1-trees">Example 1: Trees</h3>
<p><img src="slide2.png" class="img-fluid"></p>
<p><img src="slide3.png" class="img-fluid"></p>
<hr>
</section>
<section id="example-2-cholera" class="level3">
<h3 class="anchored" data-anchor-id="example-2-cholera">Example 2: Cholera</h3>
<hr>
</section>
<section id="example-3-stars-ara-constellation" class="level3">
<h3 class="anchored" data-anchor-id="example-3-stars-ara-constellation">Example 3: Stars – Ara Constellation</h3>
<p><img src="slide4.png" class="img-fluid"></p>
<p>Ref: https://www.constellation-guide.com/constellation-list/ara-constellation/ Ara was one of the 48 Greek constellations listed by the astronomer Claudius Ptolemy in the 2nd century. Ara contains two stars brighter than magnitude 3.00 and three stars located within 10 parsecs (32.6 light years) of Earth.</p>
<hr>
</section>
<section id="example-4-clinics" class="level3">
<h3 class="anchored" data-anchor-id="example-4-clinics">Example 4: Clinics</h3>
<p>Download the data from the following:</p>
<p>https://web1.capetown.gov.za/web1/OpenDataPortal/DatasetDetail?DatasetName=Clinics</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>RSA_roads <span class="ot">=</span> <span class="st">"C:/Users/01438475/OneDrive - University of Cape Town/ASDA/DataSets/zafrds8ff5a/ZAF_roads.shp"</span> <span class="sc">|&gt;</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_read</span>() <span class="sc">|&gt;</span> <span class="fu">st_transform</span>(<span class="dv">4326</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `ZAF_roads' from data source 
  `C:\Users\01438475\OneDrive - University of Cape Town\ASDA\DataSets\zafrds8ff5a\ZAF_roads.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 5559 features and 5 fields
Geometry type: MULTILINESTRING
Dimension:     XY
Bounding box:  xmin: 16.48784 ymin: -34.82747 xmax: 32.85267 ymax: -22.17693
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>RSA_biome <span class="ot">=</span> <span class="st">"C:/Users/01438475/OneDrive - University of Cape Town/ASDA/DataSets/rsabiome4xkhi/RSA_biome.shp"</span> <span class="sc">|&gt;</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_read</span>() <span class="sc">|&gt;</span> <span class="fu">st_transform</span>(<span class="dv">4326</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `RSA_biome' from data source 
  `C:\Users\01438475\OneDrive - University of Cape Town\ASDA\DataSets\rsabiome4xkhi\RSA_biome.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 3127 features and 1 field
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 16.45296 ymin: -34.8336 xmax: 32.8928 ymax: -22.12583
Geodetic CRS:  Hartebeesthoek94</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>clinics_sf <span class="ot">=</span> <span class="st">"C:/Users/01438475/OneDrive - University of Cape Town/ASDA/DataSets/Clinics/SL_CLNC.shp"</span> <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_read</span>() <span class="sc">|&gt;</span> <span class="fu">st_transform</span>(<span class="dv">4326</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `SL_CLNC' from data source 
  `C:\Users\01438475\OneDrive - University of Cape Town\ASDA\DataSets\Clinics\SL_CLNC.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 149 features and 5 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 18.34268 ymin: -34.19491 xmax: 18.90847 ymax: -33.51262
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>ct.wards_sf <span class="ot">&lt;-</span> <span class="st">"C:/Users/01438475/OneDrive - University of Cape Town/ASDA/DataSets/sa/CPT/electoral wards for cpt.shp"</span> <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_read</span>(<span class="at">quiet =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_set_crs</span>(<span class="dv">4326</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(ct.wards_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:4326 
  wkt:
GEOGCRS["WGS 84",
    ENSEMBLE["World Geodetic System 1984 ensemble",
        MEMBER["World Geodetic System 1984 (Transit)"],
        MEMBER["World Geodetic System 1984 (G730)"],
        MEMBER["World Geodetic System 1984 (G873)"],
        MEMBER["World Geodetic System 1984 (G1150)"],
        MEMBER["World Geodetic System 1984 (G1674)"],
        MEMBER["World Geodetic System 1984 (G1762)"],
        MEMBER["World Geodetic System 1984 (G2139)"],
        MEMBER["World Geodetic System 1984 (G2296)"],
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]],
        ENSEMBLEACCURACY[2.0]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Horizontal component of 3D system."],
        AREA["World."],
        BBOX[-90,-180,90,180]],
    ID["EPSG",4326]]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(clinics_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:4326 
  wkt:
GEOGCRS["WGS 84",
    ENSEMBLE["World Geodetic System 1984 ensemble",
        MEMBER["World Geodetic System 1984 (Transit)"],
        MEMBER["World Geodetic System 1984 (G730)"],
        MEMBER["World Geodetic System 1984 (G873)"],
        MEMBER["World Geodetic System 1984 (G1150)"],
        MEMBER["World Geodetic System 1984 (G1674)"],
        MEMBER["World Geodetic System 1984 (G1762)"],
        MEMBER["World Geodetic System 1984 (G2139)"],
        MEMBER["World Geodetic System 1984 (G2296)"],
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]],
        ENSEMBLEACCURACY[2.0]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Horizontal component of 3D system."],
        AREA["World."],
        BBOX[-90,-180,90,180]],
    ID["EPSG",4326]]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(clinics_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "sf"         "data.frame"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(clinics_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     LCTN               ATHY               NAME              CLASS          
 Length:149         Length:149         Length:149         Length:149        
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
     RGN                     geometry  
 Length:149         POINT        :149  
 Class :character   epsg:4326    :  0  
 Mode  :character   +proj=long...:  0  </code></pre>
</div>
</div>
<hr>
</section>
<section id="example-5-fluorspar" class="level3">
<h3 class="anchored" data-anchor-id="example-5-fluorspar">Example 5: Fluorspar</h3>
<p><img src="slide5.png" class="img-fluid"></p>
<hr>
</section>
<section id="example-6-public-electricity-lighting---from-.shp-file" class="level3">
<h3 class="anchored" data-anchor-id="example-6-public-electricity-lighting---from-.shp-file">Example 6: Public Electricity Lighting - from .shp file</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>base <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/SebnemEr/datasetsforteaching/refs/heads/main/Electricity_Public_Lighting/"</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>files <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Electricity_Public_Lighting.shp"</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Electricity_Public_Lighting.shx"</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Electricity_Public_Lighting.dbf"</span>,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Electricity_Public_Lighting.prj"</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>td <span class="ot">&lt;-</span> <span class="fu">tempdir</span>()</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (f <span class="cf">in</span> files) {</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">download.file</span>(</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(base, f),</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">file.path</span>(td, f),</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">mode =</span> <span class="st">"wb"</span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>electricity <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="fu">file.path</span>(td, <span class="st">"Electricity_Public_Lighting.shp"</span>)) <span class="sc">|&gt;</span> <span class="fu">st_transform</span>(<span class="dv">4326</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `Electricity_Public_Lighting' from data source 
  `C:\Users\01438475\AppData\Local\Temp\RtmpG2FoSL\Electricity_Public_Lighting.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 234510 features and 7 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 2039415 ymin: -4057774 xmax: 2105203 ymax: -3962912
Projected CRS: WGS 84 / Pseudo-Mercator</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(electricity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:4326 
  wkt:
GEOGCRS["WGS 84",
    ENSEMBLE["World Geodetic System 1984 ensemble",
        MEMBER["World Geodetic System 1984 (Transit)"],
        MEMBER["World Geodetic System 1984 (G730)"],
        MEMBER["World Geodetic System 1984 (G873)"],
        MEMBER["World Geodetic System 1984 (G1150)"],
        MEMBER["World Geodetic System 1984 (G1674)"],
        MEMBER["World Geodetic System 1984 (G1762)"],
        MEMBER["World Geodetic System 1984 (G2139)"],
        MEMBER["World Geodetic System 1984 (G2296)"],
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]],
        ENSEMBLEACCURACY[2.0]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Horizontal component of 3D system."],
        AREA["World."],
        BBOX[-90,-180,90,180]],
    ID["EPSG",4326]]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(electricity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "sf"         "data.frame"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>bbox <span class="ot">&lt;-</span> <span class="fu">st_bbox</span>(<span class="fu">c</span>(<span class="at">xmin =</span> <span class="fl">18.448</span>, <span class="at">ymin =</span> <span class="sc">-</span><span class="fl">33.987</span>, <span class="at">xmax =</span> <span class="fl">18.482</span>, <span class="at">ymax =</span> <span class="sc">-</span><span class="fl">33.981</span>), <span class="at">crs =</span> <span class="fu">st_crs</span>(electricity))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert bbox to an sf polygon</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>bbox_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sfc</span>(bbox)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset features that intersect with the bounding box</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>electricity_subset <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(electricity, bbox_sf)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(electricity_subset)<span class="sc">+</span><span class="fu">tm_dots</span>()<span class="sc">+</span><span class="fu">tm_basemap</span>(<span class="st">"Esri.WorldStreetMap"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># tm_basemap("Esri.WorldImagery")      # Satellite</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># tm_basemap("Esri.WorldTopoMap")      # Topographic</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># tm_basemap("Esri.WorldStreetMap")    # Streets</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># tm_basemap("CartoDB.Positron")       # Light</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="co"># tm_basemap("CartoDB.DarkMatter")     # Dark</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># tm_basemap("OpenTopoMap")            # Topographic</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="slide6.png" class="img-fluid"></p>
<hr>
</section>
<section id="example-7-on-street-parking" class="level3">
<h3 class="anchored" data-anchor-id="example-7-on-street-parking">Example 7: On Street Parking</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">=</span> <span class="st">"https://raw.githubusercontent.com/SebnemEr/datasetsforteaching/main/On_Street_Parking.geojson"</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>onstreetparking <span class="ot">&lt;-</span> <span class="fu">st_read</span>(url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `SL_TCT_PR_OS_PRKN' from data source 
  `https://raw.githubusercontent.com/SebnemEr/datasetsforteaching/main/On_Street_Parking.geojson' 
  using driver `GeoJSON'
Simple feature collection with 43122 features and 3 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 18.32217 ymin: -34.35718 xmax: 18.87689 ymax: -33.50908
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we can subset this with a ward in CoCT</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>onstreetparking_subset <span class="ot">=</span> <span class="fu">st_intersection</span>(onstreetparking, ct.wards_sf[ct.wards_sf<span class="sc">$</span>WARDNO<span class="sc">==</span><span class="dv">57</span>,])</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(onstreetparking_subset)<span class="sc">+</span><span class="fu">tm_dots</span>()<span class="sc">+</span><span class="fu">tm_basemap</span>(<span class="st">"Esri.WorldStreetMap"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><img src="slide7.png" class="img-fluid"></p>
<hr>
</section>
<section id="data-resources-for-spp-for-cape-town-municipality" class="level3">
<h3 class="anchored" data-anchor-id="data-resources-for-spp-for-cape-town-municipality">Data Resources for SPP for Cape Town Municipality</h3>
<ul>
<li><p>https://odp-cctegis.opendata.arcgis.com/search?collection=Dataset</p></li>
<li><p>https://odp.capetown.gov.za/datasets/wards/data</p></li>
<li><p>Parks</p></li>
<li><p>Wards shape file</p></li>
<li><p>MyCiti Bus Stops</p></li>
<li><p>Libraries</p></li>
</ul>
<p><a href="http://www.statssa.gov.za/?page_id=964">(Statistics by place)</a></p>
<p><a href="http://www.capetown.gov.za/Document-centre">Cape Town by documents:</a> <a href="https://geodacenter.github.io/data-and-lab/">GeoDa Center</a></p>
<hr>
</section>
<section id="what-is-common-in-all-these-examples" class="level3">
<h3 class="anchored" data-anchor-id="what-is-common-in-all-these-examples">What is common in all these examples?</h3>
<p>We have an event of interest (crime, trees, animals…etc.)</p>
<p>Point patterns are the locations of these events {<span class="math inline">\(𝒔_𝑖\)</span> }</p>
<p>Key difference from other spatial data: All points are known mapped pattern Selection bias</p>
<hr>
</section>
</section>
<section id="spatial-point-pattern-types" class="level2">
<h2 class="anchored" data-anchor-id="spatial-point-pattern-types">Spatial point pattern types</h2>
<p>Classic point pattern analysis examines the spatial location/arrangement of events represented as points on an isotropic plane, where distances are measured using straight-line (Euclidean) distance. Isotropy of a point process, defined as invariance of the distribution under rotation (Greek isos (equal) and tropos (way)), is often assumed in spatial statistics. In contrast, anisotropy occurs when spatial processes exhibit directionality, the process varies according to direction, often due to environmental factors such as prevailing winds, river flow, or steep slopes, causing interactions to depend on direction rather than distance alone (<a href="https://bpb-us-w2.wpmucdn.com/sites.umassd.edu/dist/8/406/files/2024/03/Statistical-Analysis-and-Modelling-of-Spatial-Point-Patterns-b4a075f3921cfe92.pdf">Illian et al., 2008</a>; Haase, 2001; <a href="https://doi-org/10.1016/j.spasta.2022.100716">Rajala et al., 2022</a>):</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to learn more about isotropy
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>An isotropic point process has the same statistical properties after rotation.</p>
<p><strong>Isotropy</strong> is a concept analogous to <strong>stationarity</strong>. Rather than considering translations of the point pattern, isotropy considers <strong>rotations</strong> about the origin. A point pattern is isotropic if its statistical properties remain unchanged regardless of the direction from which it is viewed.</p>
<p>In the planar case, a rotation is described by an angle <span class="math inline">\(\theta \in [0^\circ,360^\circ]\)</span>. If</p>
<p><span class="math display">\[
Z(s_1,s_2)
\]</span></p>
<p>is a point in <span class="math inline">\(\mathbb{R}^2\)</span> with coordinates <span class="math inline">\(s_1\)</span> and <span class="math inline">\(s_2\)</span>, then rotating the point by an angle <span class="math inline">\(\theta\)</span> about the origin gives the new coordinates</p>
<p><span class="math display">\[
s_1^{\theta} = s_1 \cos\theta + s_2\sin\theta,
\]</span></p>
<p>and</p>
<p><span class="math display">\[
s_2^{\theta} = -s_1 \sin\theta + s_2 \cos\theta.
\]</span></p>
<p>Although an individual point has no orientation, its location can be rotated about the origin. A point process</p>
<p><span class="math display">\[
{Z_1, Z_2, \ldots\, Z_N}
\]</span></p>
<p>is <strong>isotropic</strong> if the rotated point process</p>
<p><span class="math display">\[
{R_\theta Z_1, R_\theta Z_2, \ldots\, R_\theta Z_N}
\]</span></p>
<p>has the same probability distribution as the original point process for every rotation angle <span class="math inline">\(\theta\)</span>. Notice that we are not asking whether the points end up in the same places, they won’t. Instead, we ask whether the pattern looks statistically the same.</p>
<p>Isotropy refers to the distribution of the entire point pattern remaining unchanged under such rotations, not to the orientation of individual points.</p>
</div>
</div>
</div>
<hr>
<p>Point pattern analysis can be classified according to the types of events being analysed:</p>
<p><strong>(a) Univariate point patterns.</strong> In the simplest case, all points represent the same type of event and differ only in their spatial location. The objective is to determine whether the events are randomly distributed, clustered, or regularly spaced. This is known as <strong>univariate point pattern analysis</strong>.</p>
<p>Suppose we map the locations of bicycle thefts in a city over one year. We may ask whether the thefts are randomly distributed, concentrated in hotspots, or evenly spaced across the city.</p>
<p><strong>(b) Bivariate point patterns.</strong> When two different types of events are present, the focus is on their spatial relationship. For example, we may ask whether two plant species occur independently, whether one species tends to occur near the other, or whether supermarkets and liquor stores; airbnbs and hotels are co-located or spatially separated. These questions are addressed using <strong>bivariate point pattern analysis</strong>.</p>
<p>A public health researcher may investigate whether fast-food restaurants tend to be located near schools, or whether the two types of locations are spatially independent.</p>
<p><strong>(c) Multivariate point patterns.</strong> If there are more than two event types, the analysis becomes <strong>multivariate</strong>, allowing the investigation of spatial relationships among multiple categories of objects simultaneously.</p>
<section id="marked-point-patterns" class="level3">
<h3 class="anchored" data-anchor-id="marked-point-patterns">Marked point patterns</h3>
<p>In many applications, points are associated with additional information known as <strong>marks</strong>. Marks are attributes attached to each event and may be either qualitative (categorical) or quantitative (continuous).</p>
<p><strong>(d) Qualitative marks.</strong> A qualitative mark describes a category or class. For example, each tree in a forest may be classified as <em>alive</em> or <em>dead</em>, allowing us to investigate whether dead trees occur in clusters.</p>
<p>Suppose we map the locations of traffic accidents. Each accident can be marked as either <strong>fatal</strong> or <strong>non-fatal</strong>. We can then investigate whether fatal accidents are more clustered than non-fatal accidents.</p>
<p><strong>(e) Quantitative marks.</strong> A quantitative mark is a numerical measurement associated with each event. For example, each tree may have a recorded diameter or height, enabling us to examine whether tree size is related to the spacing between neighbouring trees.</p>
<p>Suppose each crime incident is assigned the monetary value of property stolen. We can investigate whether high-value thefts tend to occur closer together than low-value thefts.</p>
</section>
<section id="key-terminology" class="level3">
<h3 class="anchored" data-anchor-id="key-terminology">Key terminology</h3>
<p>It is important to distinguish the following concepts in point pattern analysis:</p>
</section>
</section>
<section id="key-terminology-1" class="level2">
<h2 class="anchored" data-anchor-id="key-terminology-1">Key Terminology</h2>
<p>It is important to distinguish between the following concepts:</p>
<ul>
<li><strong>Event:</strong> The phenomenon being observed (e.g., a traffic accident, burglary, tree, or disease case).</li>
<li><strong>Location:</strong> The spatial coordinates <span class="math inline">\((s_1, s_2)\)</span> or <span class="math inline">\((x,y)\)</span> at which the event occurs.</li>
<li><strong>Mark:</strong> An attribute attached to an event, such as accident severity, tree species, or burglary value.</li>
<li><strong>Covariate:</strong> An external variable that may influence the occurrence of events but is not itself an event. Examples include population density, distance to major roads, elevation, land use, or average household income.</li>
</ul>
<p><img src="pointtypes.png" class="img-fluid"> Ref: [7], page 12, Figure 2.1</p>
<section id="displaced-amacrine-cells-in-the-retina-of-a-rabbit-analysis-of-a-bivariate-spatial-point-pattern-by-peter-j.-diggle-1986" class="level3">
<h3 class="anchored" data-anchor-id="displaced-amacrine-cells-in-the-retina-of-a-rabbit-analysis-of-a-bivariate-spatial-point-pattern-by-peter-j.-diggle-1986">Displaced amacrine cells in the retina of a rabbit: analysis of a bivariate spatial point pattern by <a href="https://www-sciencedirect-com/science/article/abs/pii/0165027086901159">Peter J. Diggle (1986)</a></h3>
<p>A data set consisting of the locations of “light-on” and “light-off” displaced amacrine cells in the retina of a rabbit. The two cell types, labelled ‘on’ and ‘off’, are distinguished by their response to visual stimuli. Cells of the same type are evenly spaced, indicating a regular point pattern. A natural question is whether the spatial distributions of the two cell types are independent, or whether they influenced each other’s development.</p>
<p><img src="onoff.png" class="img-fluid"></p>
<p>Ref: [3], page: 5, Figure 1.5</p>
</section>
</section>
<section id="spatial-point-pattern-types-g-point-networks" class="level2">
<h2 class="anchored" data-anchor-id="spatial-point-pattern-types-g-point-networks">Spatial Point Pattern Types – (g) Point Networks</h2>
<ul>
<li>So far we looked at points in space but remember earlier I showed an example of public electricity lighting.</li>
<li>Here you can see the events (electricity lighting) are located on an actual network, ie. road network, rather than space.</li>
<li>So we cannot use straight lines to calculate the distances but we need to use a network distance.</li>
</ul>
</section>
<section id="what-is-the-research-question-here" class="level2">
<h2 class="anchored" data-anchor-id="what-is-the-research-question-here">What is the research question here?</h2>
<p>Why do we analyse these point patterns? There are two research questions we are interested to answer:</p>
<ol type="1">
<li>Is the pattern random or structured in a way? (exploratory SPP):</li>
</ol>
<ul>
<li>Completely spatially random</li>
<li>Clustered pattern</li>
<li>Regular pattern</li>
</ul>
<ol start="2" type="1">
<li>What is the process that might have generated this pattern? Covariates etc. (Inferential SPP)</li>
</ol>
<p>We will deal with univariate patterns to start with and in the case of trees and forests, the research question is whether the forest density depends on the terrain, elevation and whether, after accounting for the influence of covariates, there is evidence of spatial clustering of the trees.</p>
</section>
</section>
<section id="univariate-point-patterns" class="level1">
<h1>Univariate point patterns</h1>
<section id="exploratory-analysis---intensity" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-analysis---intensity">Exploratory analysis - Intensity</h2>
<p>The intensity of a point pattern measures how many events occur, on average, within a given unit of area. It is one of the most important descriptive characteristics of a point process and is typically the first property investigated during spatial point pattern analysis. Intensity is analogous to the mean of a numerical dataset, providing a measure of the average occurrence of events in space. Since it can be estimated with relatively few modelling assumptions, it serves as a useful starting point for understanding the overall spatial distribution before investigating higher-order properties such as clustering or interaction between events.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click here for the difference between density and intensity
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Density describes what you observed in your dataset (events per unit area). Intensity describes the underlying point process that generated those observations. In practice, the observed density is used to estimate the process intensity. Consequently, the terms are often used interchangeably in introductory point pattern analysis, although intensity is the preferred statistical term.</p>
</div>
</div>
</div>
<p>Summary statistics are used to describe the main characteristics of a point pattern. They provide information about the average behaviour of the spatial process, such as the overall intensity or degree of clustering, as well as the variation around this average. By comparing the observed summary statistics with those expected under an appropriate null model (for example, Complete Spatial Randomness), we can determine whether the observed spatial pattern is likely to have arisen by chance or whether it exhibits significant clustering, regularity, or other forms of spatial structure.</p>
</section>
<section id="intensity---homogeneous" class="level2">
<h2 class="anchored" data-anchor-id="intensity---homogeneous">Intensity - Homogeneous</h2>
<p>Figure 6.1: Examples of approximately homogeneous point patterns. Although the events may exhibit clustering or regular spacing, the overall intensity remains relatively constant across the study region.</p>
<p><img src="intensityhomo.png" class="img-fluid"> ::: {.content-visible when-format=“pdf”}</p>
<p>Classic point pattern datasets with (roughly) homogeneous intensity. Left: biological cell centres in histological section [572, 575]. Middle: trees in a New Zealand forest, excluding a five-foot border [441, 575]. Right: Swedish Pine saplings [642, 572]. :::</p>
</section>
<section id="intensity---inhomogeneous" class="level2">
<h2 class="anchored" data-anchor-id="intensity---inhomogeneous">Intensity - Inhomogeneous</h2>
<p>Figure 6.2. Examples of inhomogeneous point patterns. Here the event intensity varies across the study area because of underlying environmental, biological, or geological processes. Before analysing clustering or interaction, this spatial variation in intensity should be accounted for.</p>
<p><img src="intensityinhomo.png" class="img-fluid"></p>
</section>
<section id="intensity" class="level2">
<h2 class="anchored" data-anchor-id="intensity">Intensity</h2>
<p>A point pattern is an observed <strong>realisation</strong> of an underlying spatial point process. The process is characterised by its <strong>intensity</strong>, denoted by <span class="math inline">\(\lambda\)</span>, which represents the expected number of events per unit area. Because the true intensity is unknown, it is estimated from the observed point pattern.</p>
<p>The simplest estimator of the intensity is</p>
<p><span class="math display">\[
\hat{\lambda} = \frac{n(X)}{|A|},
\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(n(X)\)</span> is the total number of observed events in the study region,</li>
<li><span class="math inline">\(|A|\)</span> is the area of the observation window.</li>
</ul>
<p>The estimate <span class="math inline">\(\hat{\lambda}\)</span> is simply the <strong>observed density</strong> (events per unit area) and is an unbiased estimator of the true process intensity <span class="math inline">\(\lambda\)</span>.</p>
<section id="units-of-intensity" class="level3">
<h3 class="anchored" data-anchor-id="units-of-intensity">Units of Intensity</h3>
<p>The value of the intensity depends on the units used to measure the study region. For example,</p>
<ul>
<li>25 events per km<span class="math inline">\(^2\)</span>,</li>
<li>0.25 events per hectare,</li>
<li>0.000025 events per m<span class="math inline">\(^2\)</span>.</li>
</ul>
<p>It is therefore important to always report the units associated with the study area.</p>
</section>
<section id="defining-the-observation-window" class="level3">
<h3 class="anchored" data-anchor-id="defining-the-observation-window">Defining the Observation Window</h3>
<p>The estimated intensity depends directly on the area of the <strong>observation window</strong>. Choosing an appropriate study region is therefore an important part of point pattern analysis.</p>
<p>Historically, many theoretical examples assumed that the observation window was rescaled to a <strong>unit square</strong> to simplify mathematical derivations. While useful for understanding the underlying concepts, this assumption is rarely realistic for applied studies.</p>
<p>Modern GIS software allows the observation window to be defined in several ways, including:</p>
<ul>
<li>the actual study area boundary (e.g., an administrative region or nature reserve),</li>
<li>a rectangular bounding box surrounding the data,</li>
<li>a convex hull that encloses all observed points (fitting around the points tightly),</li>
<li>another polygon representing the area within which events could have occurred.</li>
</ul>
<p>The observation window should represent the region in which events were able to occur and be observed, rather than simply the area occupied by the observed points.</p>
</section>
</section>
<section id="intensity-example-1-swedishpines-data-bounding-box-rectangular" class="level2">
<h2 class="anchored" data-anchor-id="intensity-example-1-swedishpines-data-bounding-box-rectangular">Intensity Example 1: swedishpines data – Bounding Box (Rectangular)</h2>
<p>We are going to look at the swedishpines dataset from spatstat package. We count the number of pine trees: 71 points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(swedishpines)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(swedishpines)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ppp"</code></pre>
</div>
</div>
<p>This indicates that this is a planar point pattern (ppp).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>swedishpines</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern: 71 points
window: rectangle = [0, 96] x [0, 100] units (one unit = 0.1 metres)</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Window</span>(swedishpines)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>window: rectangle = [0, 96] x [0, 100] units (one unit = 0.1 metres)</code></pre>
</div>
</div>
<p>Clearly the area here is <span class="math inline">\((96-0)*(100-0) = 9600\)</span> units sq. Since 1 unit is 0.1 metres, then the area is 96 metre square. <span class="math inline">\(\lambda=71/96=0.7396\)</span> points (trees) per metre square.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">intensity</span>(spatstat.geom<span class="sc">::</span><span class="fu">rescale</span>(swedishpines))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7395833</code></pre>
</div>
</div>
</section>
<section id="intensity-example-2-clinics-in-ct-2016---bounding-polygon-irregular" class="level2">
<h2 class="anchored" data-anchor-id="intensity-example-2-clinics-in-ct-2016---bounding-polygon-irregular">Intensity Example 2: clinics in CT 2016 - Bounding Polygon (Irregular )</h2>
<ul>
<li>We count the number of clinics</li>
<li>Calculate the area of City of CT: (search on google) 2445km-square</li>
<li><span class="math inline">\(\lambda=149/2445=0.0609407\)</span></li>
</ul>
<p>Now this is based on irregular bounding polygon. We could use a regular bounding box, such as a rectangle.</p>
<section id="intensity-under-different-polygons-and-bounding-box-measures" class="level3">
<h3 class="anchored" data-anchor-id="intensity-under-different-polygons-and-bounding-box-measures">Intensity under different polygons and bounding box measures</h3>
<ul>
<li><p>The intensity is very sensitive so as to what bounding box or polygon you use.</p></li>
<li><p>Try this for the clinics dataset.</p></li>
</ul>
</section>
</section>
</section>
<section id="properties-of-csr" class="level1">
<h1>Properties of CSR</h1>
<p>Question 1) Is the pattern random or structured in a way? (exploratory SPP)</p>
<p>Do the spatial locations appear completely spatially random? Are the locations homogeneously distributed in the specified area? Or are they clustered?</p>
<section id="complete-spatial-randomness-homogeneous-poisson-process-regularity-and-clustering" class="level2">
<h2 class="anchored" data-anchor-id="complete-spatial-randomness-homogeneous-poisson-process-regularity-and-clustering">Complete Spatial Randomness (homogeneous Poisson process), Regularity and Clustering</h2>
<ul>
<li><p>Spatial point patterns can be</p>
<ul>
<li>completely random</li>
<li>regular</li>
<li>clustered</li>
</ul></li>
<li><p>The standard against which spatial point patterns are often compared is a completely spatially random (CSR) point process which is sometimes called homogeneous Poisson process.</p></li>
<li><p>We can do some plots and observe the pattern however usually we need some quantification since looking at plots may be different from eye to eye.</p></li>
<li><p>How do we quantify the spatial locations?</p></li>
</ul>
<hr>
<section id="complete-spatial-randomness-homogeneous-poisson-process" class="level3">
<h3 class="anchored" data-anchor-id="complete-spatial-randomness-homogeneous-poisson-process">Complete Spatial Randomness (homogeneous Poisson process)</h3>
<p>Throughout these notes, the following notation will be used:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Symbol</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(A\)</span></td>
<td style="text-align: left;">The observation window (study region) in which the point pattern is observed.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(a_j\)</span></td>
<td style="text-align: left;">The <span class="math inline">\(j\)</span>th subregion (or <strong>quadrat</strong>), where <span class="math inline">\(j = 1,\ldots,m\)</span>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(m\)</span></td>
<td style="text-align: left;">The total number of quadrats into which the study region is divided.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(|A|\)</span></td>
<td style="text-align: left;">The area of the observation window, measured in square units.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(|a_j|\)</span></td>
<td style="text-align: left;">The area of the <span class="math inline">\(j\)</span>th quadrat. If all quadrats are of equal size, then <span class="math inline">\(|a_j| = |A|/m\)</span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(n(X)\)</span></td>
<td style="text-align: left;">The total number of observed events (points) within the observation window <span class="math inline">\(A\)</span>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\lambda\)</span></td>
<td style="text-align: left;">The true intensity of the underlying point process, defined as the expected number of events per unit area.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\hat{\lambda}\)</span></td>
<td style="text-align: left;">The estimated intensity of the point pattern, given by:</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\hat{\lambda} = \frac{n(X)}{|A|}.
\]</span></p>
<p>Under a <strong>homogeneous Poisson process</strong>, <span class="math inline">\(\hat{\lambda}\)</span> is both the maximum likelihood estimator and an unbiased estimator of the true intensity <span class="math inline">\(\lambda\)</span>.</p>
<p>In quadrat-based analyses, the expected number of events in each quadrat is</p>
<p><span class="math display">\[
E[n(a_j)] = \lambda |a_j|,
\]</span></p>
<p>where <span class="math inline">\(n(a_j)\)</span> denotes the number of points observed in quadrat <span class="math inline">\(a_j\)</span>.</p>
<hr>
</section>
</section>
<section id="complete-spatial-randomness-csr" class="level2">
<h2 class="anchored" data-anchor-id="complete-spatial-randomness-csr">Complete Spatial Randomness (CSR)</h2>
<p>A point pattern is said to satisfy <strong>Complete Spatial Randomness (CSR)</strong> if two conditions hold:</p>
<ol type="1">
<li><p><strong>The number of events in any region follows a Poisson distribution.</strong></p>
<p>For a quadrat <span class="math inline">\(a_j\)</span> with area <span class="math inline">\(|a_j|\)</span>, the number of observed events,</p>
<p><span class="math display">\[
n(a_j),
\]</span></p>
<p>follows a Poisson distribution with mean</p>
<p><span class="math display">\[
\lambda |a_j|,
\]</span></p>
<p>where <span class="math inline">\(\lambda\)</span> is the intensity of the point process. In practice, the intensity is estimated by</p>
<p><span class="math display">\[
\hat{\lambda} = \frac{n(X)}{|A|},
\]</span></p>
<p>so the expected number of events in quadrat <span class="math inline">\(a_j\)</span> is</p>
<p><span class="math display">\[
E[n(a_j)] = \hat{\lambda}|a_j|.
\]</span></p></li>
<li><p><strong>Events are independently and uniformly distributed.</strong></p>
<p>Conditional on observing <span class="math inline">\(n\)</span> events within a region, the locations of those events are independent of one another and are equally likely to occur anywhere within the observation window.</p></li>
</ol>
<p>Together, these two assumptions imply that the point pattern exhibits no clustering, regularity, or directional preference beyond what would be expected by chance.</p>
</section>
<section id="methods-for-assessing-csr" class="level2">
<h2 class="anchored" data-anchor-id="methods-for-assessing-csr">Methods for Assessing CSR</h2>
<p>Several statistical methods can be used to determine whether an observed point pattern departs from Complete Spatial Randomness.</p>
<section id="first-order-methods" class="level3">
<h3 class="anchored" data-anchor-id="first-order-methods">First-order methods</h3>
<p>These methods describe variation in the intensity of the point pattern.</p>
<ul>
<li><strong>Intensity estimation</strong> – estimates the average number of events per unit area and identifies whether the process is homogeneous or inhomogeneous.</li>
<li><strong>Quadrat count analysis</strong> – divides the study region into equal-sized quadrats and compares the observed and expected number of events using a chi-square test.</li>
<li><strong>Scan statistics</strong> – searches for localised clusters of unusually high or low event intensity. Common approaches include:
<ul>
<li>Kulldorff’s spatial scan statistic,</li>
<li>STAC (Spatial and Temporal Analysis of Crime),</li>
<li>Generalised Additive Models (GAMs) for estimating spatial intensity surfaces.</li>
</ul></li>
</ul>
</section>
<section id="distance-based-methods" class="level3">
<h3 class="anchored" data-anchor-id="distance-based-methods">Distance-based methods</h3>
<p>These methods investigate the spacing between events.</p>
<ul>
<li><strong>Nearest-neighbour (<span class="math inline">\(G\)</span>) function</strong> – analyses the distribution of distances from each event to its nearest neighbouring event.</li>
<li><strong>Empty-space (<span class="math inline">\(F\)</span>) function</strong> – analyses the distribution of distances from randomly selected locations to the nearest observed event.</li>
</ul>
</section>
<section id="second-order-methods" class="level3">
<h3 class="anchored" data-anchor-id="second-order-methods">Second-order methods</h3>
<p>Second-order statistics examine the dependence between events over a range of spatial scales.</p>
<p>Examples include:</p>
<ul>
<li>Ripley’s <span class="math inline">\(K\)</span> function,</li>
<li>the pair correlation function <span class="math inline">\(g(r)\)</span>,</li>
<li>Besag’s <span class="math inline">\(L\)</span> function.</li>
</ul>
<p>These methods are used to determine whether events are clustered, randomly distributed, or regularly spaced at different distances.</p>
</section>
</section>
</section>
<section id="quadrat-counting-and-tests" class="level1">
<h1>Quadrat Counting and Tests</h1>
<section id="quadrat-counting---poisson-process" class="level2">
<h2 class="anchored" data-anchor-id="quadrat-counting---poisson-process">Quadrat Counting - Poisson Process</h2>
</section>
<section id="quadrat-count-analysis" class="level2">
<h2 class="anchored" data-anchor-id="quadrat-count-analysis">Quadrat Count Analysis</h2>
<p>When the intensity of a point pattern is suspected to vary across the study region, it can be estimated <strong>non-parametrically</strong> using methods such as <strong>quadrat counting</strong> or <strong>kernel density estimation</strong>. Quadrat counting provides a simple way to assess whether the observed pattern is consistent with Complete Spatial Randomness (CSR).</p>
<p>The basic procedure is as follows:</p>
<ol type="1">
<li><p>Divide the observation window <span class="math inline">\(A\)</span> into <span class="math inline">\(m\)</span> subregions (quadrats),</p>
<p><span class="math display">\[
a_1, a_2, \ldots, a_m,
\]</span></p>
<p>typically of equal area.</p></li>
<li><p>Count the number of events in each quadrat,</p>
<p><span class="math display">\[
n_j = n(X \cap a_j), \qquad j = 1,\ldots,m,
\]</span></p>
<p>where <span class="math inline">\(n_j\)</span> is the number of observed events in quadrat <span class="math inline">\(a_j\)</span>.</p></li>
<li><p>Calculate the average number of events per quadrat,</p>
<p><span class="math display">\[
\lambda_m = \frac{n(X)}{m},
\]</span></p>
<p>assuming that all quadrats have equal area.</p></li>
</ol>
<p>Under the assumption of <strong>Complete Spatial Randomness (CSR)</strong>, the number of events in each quadrat follows a Poisson distribution. The probability of observing exactly <span class="math inline">\(k\)</span> events in a quadrat is therefore</p>
<p><span class="math display">\[
P(X = k) =
\frac{\lambda_m^k e^{-\lambda_m}}{k!},
\qquad
k = 0,1,2,\ldots,
\]</span></p>
<p>where <span class="math inline">\(\lambda_m\)</span> is the expected number of events per quadrat.</p>
<p>The observed frequencies of quadrats containing <span class="math inline">\(0, 1, 2, \ldots\)</span> events are then compared with the expected frequencies under the Poisson distribution, typically using a <strong>chi-square goodness-of-fit test</strong>.</p>
<p>A significant difference between the observed and expected frequencies suggests that the point pattern departs from Complete Spatial Randomness. Such departures may indicate clustering, regular spacing, or spatial variation in intensity.</p>
<section id="example-simulated-csr-data" class="level3">
<h3 class="anchored" data-anchor-id="example-simulated-csr-data">Example – Simulated CSR Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate CSR with exactly 100 points</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>pp_csr <span class="ot">&lt;-</span> <span class="fu">runifpoint</span>(</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="dv">100</span>,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">win =</span> <span class="fu">owin</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(pp_csr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ppp"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pp_csr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>Q10x10_csr <span class="ot">=</span> <span class="fu">quadratcount</span>(pp_csr, <span class="at">nx=</span><span class="dv">10</span>, <span class="at">ny=</span><span class="dv">10</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pp_csr)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Q10x10_csr, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"white"</span>, <span class="at">cex=</span><span class="fl">0.005</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="quadrat-counts" class="level3">
<h3 class="anchored" data-anchor-id="quadrat-counts">Quadrat counts</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  pp_csr,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Simulated CSR pattern with quadrat counts"</span>,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">1</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  Q10x10_csr,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">add =</span> <span class="cn">TRUE</span>,</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"red"</span>,</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex =</span> <span class="fl">0.8</span>,</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">lty =</span> <span class="dv">2</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/plot-quadrat-counts-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="comparing-observed-and-expected-quadrat-counts" class="level2">
<h2 class="anchored" data-anchor-id="comparing-observed-and-expected-quadrat-counts">Comparing observed and expected quadrat counts</h2>
<p>Suppose a point pattern contains <span class="math inline">\(n=100\)</span> events and the observation window is divided into <span class="math inline">\(m=100\)</span> equal-sized quadrats. The estimated mean number of events per quadrat is</p>
<p><span class="math display">\[
\hat{\lambda}_m = \frac{n}{m}
                = \frac{100}{100}
                = 1.
\]</span></p>
<p>Under Complete Spatial Randomness, the number of events in a quadrat follows a Poisson distribution:</p>
<p><span class="math display">\[
P(N=k) = \frac{\hat{\lambda}_m^k e^{-\hat{\lambda}_m}}{k!},
\qquad
k=0,1,2,\ldots
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat.geom)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat.random)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of events and quadrats</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>n_events <span class="ot">&lt;-</span> <span class="fu">npoints</span>(pp_csr)</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>m_quadrats <span class="ot">&lt;-</span> <span class="fu">length</span>(Q10x10_csr)</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean number of events per quadrat</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>lambda_m <span class="ot">&lt;-</span> n_events <span class="sc">/</span> m_quadrats</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>lambda_m</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<section id="observed-and-expected-proportions" class="level3">
<h3 class="anchored" data-anchor-id="observed-and-expected-proportions">Observed and expected proportions</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(Q10x10_csr)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>observed_frequency <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">table</span>(counts))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Observed proportion</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>observed_proportion <span class="ot">&lt;-</span> observed_frequency<span class="sc">/</span> <span class="dv">100</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected Poisson proportion</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>expected_proportion <span class="ot">&lt;-</span> <span class="fu">dpois</span>(</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="dv">0</span><span class="sc">:</span><span class="dv">5</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">lambda =</span> lambda_m</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>quadrat_summary <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">k =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">5</span>,</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Number of quadrats</span><span class="st">`</span> <span class="ot">=</span> observed_frequency,</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Observed proportion</span><span class="st">`</span> <span class="ot">=</span> observed_proportion,</span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Expected proportion</span><span class="st">`</span> <span class="ot">=</span> expected_proportion</span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a>  quadrat_summary,</span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">5</span>),</span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">align =</span> <span class="fu">c</span>(<span class="st">"c"</span>, <span class="st">"c"</span>, <span class="st">"c"</span>, <span class="st">"c"</span>),</span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Observed and expected quadrat frequencies under CSR"</span></span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Observed and expected quadrat frequencies under CSR</caption>
<thead>
<tr class="header">
<th style="text-align: center;">k</th>
<th style="text-align: center;">Number of quadrats</th>
<th style="text-align: center;">Observed proportion</th>
<th style="text-align: center;">Expected proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">0.33</td>
<td style="text-align: center;">0.36788</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">0.42</td>
<td style="text-align: center;">0.36788</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">0.18394</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.03</td>
<td style="text-align: center;">0.06131</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.01533</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.00307</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The expected probabilities are calculated as follows:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 55%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(k\)</span></th>
<th style="text-align: left;">Expected probability</th>
<th style="text-align: left;">Calculation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: left;">0.36788</td>
<td style="text-align: left;"><span class="math inline">\(\displaystyle \frac{1^0e^{-1}}{0!}=e^{-1}=0.36788\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: left;">0.36788</td>
<td style="text-align: left;"><span class="math inline">\(\displaystyle \frac{1^1e^{-1}}{1!}=e^{-1}=0.36788\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: left;">0.18394</td>
<td style="text-align: left;"><span class="math inline">\(\displaystyle \frac{1^2e^{-1}}{2!}=\frac{e^{-1}}{2}=0.18394\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: left;">0.06131</td>
<td style="text-align: left;"><span class="math inline">\(\displaystyle \frac{1^3e^{-1}}{3!}=\frac{e^{-1}}{6}=0.06131\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: left;">0.01533</td>
<td style="text-align: left;"><span class="math inline">\(\displaystyle \frac{1^4e^{-1}}{4!}=\frac{e^{-1}}{24}=0.01533\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: left;">0.00307</td>
<td style="text-align: left;"><span class="math inline">\(\displaystyle \frac{1^5e^{-1}}{5!}=\frac{e^{-1}}{120}=0.00307\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">6</td>
<td style="text-align: left;">0.00051</td>
<td style="text-align: left;"><span class="math inline">\(\displaystyle \frac{1^6e^{-1}}{6!}=\frac{e^{-1}}{720}=0.00051\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="graphical-comparison" class="level3">
<h3 class="anchored" data-anchor-id="graphical-comparison">Graphical comparison</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> quadrat_summary <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>    k,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Observed proportion</span><span class="st">`</span>,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Expected proportion</span><span class="st">`</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_longer</span>(</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="sc">-</span>k,</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"Proportion type"</span>,</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"Proportion"</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>  plot_data,</span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">factor</span>(k),</span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> Proportion,</span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">`</span><span class="at">Proportion type</span><span class="st">`</span></span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(</span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.8</span>),</span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="fl">0.7</span></span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb44-25"><a href="#cb44-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb44-26"><a href="#cb44-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Number of events per quadrat, k"</span>,</span>
<span id="cb44-27"><a href="#cb44-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion of quadrats"</span>,</span>
<span id="cb44-28"><a href="#cb44-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="cn">NULL</span></span>
<span id="cb44-29"><a href="#cb44-29" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb44-30"><a href="#cb44-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb44-31"><a href="#cb44-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb44-32"><a href="#cb44-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"bottom"</span></span>
<span id="cb44-33"><a href="#cb44-33" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/plot-observed-expected-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="example-calculation" class="level3">
<h3 class="anchored" data-anchor-id="example-calculation">Example calculation</h3>
<p>The probability of observing exactly three events in a quadrat is</p>
<p><span class="math display">\[
P(N=3)
=
\frac{1^3e^{-1}}{3!}
=
0.0613.
\]</span></p>
<p>Therefore, under CSR, approximately <strong>6.13% of the quadrats</strong> are expected to contain exactly three events.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.06131324</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="quadrat-counting---chi-square-test" class="level1">
<h1>Quadrat Counting - Chi-Square Test</h1>
<p>When the intensity of a point pattern is suspected to vary across the study region, it can be explored using <strong>non-parametric</strong> methods such as <strong>quadrat counting</strong> or <strong>kernel density estimation</strong>. Quadrat counting provides a simple way to compare the observed distribution of events with that expected under <strong>Complete Spatial Randomness (CSR)</strong>.</p>
<p>The quadrat count procedure consists of the following steps:</p>
<ol type="1">
<li><p>Partition the observation window <span class="math inline">\(A\)</span> into <span class="math inline">\(m\)</span> subregions (quadrats),</p>
<p><span class="math display">\[
a_1, a_2, \ldots, a_m,
\]</span></p>
<p>typically of equal area.</p></li>
<li><p>Count the number of events in each quadrat,</p>
<p><span class="math display">\[
n_j = n(X \cap a_j),
\qquad
j = 1,\ldots,m,
\]</span></p>
<p>where <span class="math inline">\(n_j\)</span> is the number of observed events in quadrat <span class="math inline">\(a_j\)</span>.</p></li>
<li><p>Compute the expected number of events in each quadrat,</p>
<p><span class="math display">\[
e_j = \hat{\lambda}|a_j|,
\]</span></p>
<p>where</p>
<p><span class="math display">\[
\hat{\lambda}=\frac{n(X)}{|A|}
\]</span></p>
<p>is the estimated intensity of the point process.</p></li>
<li><p>Compare the observed and expected counts using Pearson’s chi-square goodness-of-fit statistic,</p></li>
</ol>
<p><span class="math display">\[
\chi^2
=
\sum_{j=1}^{m}
\frac{(n_j-e_j)^2}{e_j}
=
\sum_{j=1}^{m}
\frac{(n_j-\hat{\lambda}|a_j|)^2}
{\hat{\lambda}|a_j|}.
\]</span></p>
<p>Under the null hypothesis of <strong>Complete Spatial Randomness</strong>, the test statistic approximately follows a chi-square distribution,</p>
<p><span class="math display">\[
\chi^2
\sim
\chi^2_{m-1},
\]</span></p>
<p>where <span class="math inline">\(m-1\)</span> is the number of degrees of freedom. (Degrees of freedom is actually the number of categories − 1 − number of estimated parameters. So when the intensity is estimated from the data (as it usually is), the asymptotic degrees of freedom are often taken as m−2.)</p>
<p>A large value of the chi-square statistic indicates that the observed quadrat counts differ substantially from those expected under CSR, suggesting that the point pattern is <strong>not</strong> completely spatially random. Such departures may arise from clustering, regular spacing, or spatial variation in intensity.</p>
<section id="quadrat-counting-observed-point-counts-n_j" class="level2">
<h2 class="anchored" data-anchor-id="quadrat-counting-observed-point-counts-n_j">Quadrat counting – Observed point counts (<span class="math inline">\(n_j\)</span>)</h2>
<p>Let us first standardize the region.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>swp <span class="ot">&lt;-</span>spatstat.geom<span class="sc">::</span><span class="fu">rescale</span>(swedishpines)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(swp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<p>Let us partition the area into 3x3 equal subregions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>Q3x3 <span class="ot">=</span> <span class="fu">quadratcount</span>(swp, <span class="at">nx=</span><span class="dv">3</span>, <span class="at">ny=</span><span class="dv">3</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(swp)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Q3x3, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">cex=</span><span class="fl">1.5</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>Q3x3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             x
y             [0,3.2] (3.2,6.4] (6.4,9.6]
  (6.67,10]         8         6         7
  (3.33,6.67]       8        11         9
  [0,3.33]          5         6        11</code></pre>
</div>
</div>
<hr>
</section>
<section id="quadrat-counting-expected-point-counts-e_j" class="level2">
<h2 class="anchored" data-anchor-id="quadrat-counting-expected-point-counts-e_j">Quadrat counting – Expected point counts (<span class="math inline">\(e_j\)</span>)</h2>
<ul>
<li>The estimated mean point intensity is:</li>
</ul>
<p><span class="math display">\[
\bar{\lambda}
=
\frac{n}{|A|}
=
\frac{71\ \text{points}}{96\ \text{sq-metres}}
=
0.73958
\]</span></p>
<ul>
<li>The area of each quadrat is:</li>
</ul>
<p><span class="math display">\[
|a_j|
=
\frac{|A|}{m}
=
\frac{96}{9}
=
10.66667
\]</span></p>
<ul>
<li>The expected number of points in each quadrat is:</li>
</ul>
<p><span class="math display">\[
e_j
=
\bar{\lambda}|a_j|
=
\frac{n}{m}
=
0.73958 \times 10.66667
=
7.88889
\]</span></p>
<p>Since the subregions are equal in size, we could simply calculate:</p>
<p><span class="math display">\[
e_j = \frac{71}{9} = 7.88889
\]</span></p>
<p>The chi-squared statistic is:</p>
<p><span class="math display">\[
\chi^2
=
\sum_{j=1}^{9}
\frac{(n_j-e_j)^2}{e_j}
\]</span></p>
<p>Using the observed quadrat counts:</p>
<p><span class="math display">\[
\begin{aligned}
\chi^2
={}&amp;
2 \times \frac{(8-7.89)^2}{7.89}
+
2 \times \frac{(6-7.89)^2}{7.89}
+
\frac{(7-7.89)^2}{7.89}
\\[4pt]
&amp;+
2 \times \frac{(11-7.89)^2}{7.89}
+
\frac{(9-7.89)^2}{7.89}
+
\frac{(5-7.89)^2}{7.89}
\\[4pt]
={}&amp;
\frac{36.89}{7.89}
=
4.676
\end{aligned}
\]</span></p>
</section>
<section id="quadrat-counting-expected-point-counts-e_j-in-r" class="level2">
<h2 class="anchored" data-anchor-id="quadrat-counting-expected-point-counts-e_j-in-r">Quadrat counting – Expected point counts (<span class="math inline">\(e_j\)</span>) in R</h2>
<ul>
<li>The estimated mean point intensity is:</li>
</ul>
<p><span class="math display">\[
\bar{\lambda}
=
\frac{n}{|A|}
=
\frac{71\ \text{points}}{96\ \text{sq-metres}}
=
0.73958
\]</span></p>
<ul>
<li>The area of each quadrat is:</li>
</ul>
<p><span class="math display">\[
|a_j|
=
\frac{|A|}{m}
=
\frac{96}{9}
=
10.66667
\]</span></p>
<ul>
<li>The expected number of points in each quadrat is:</li>
</ul>
<p><span class="math display">\[
e_j
=
\bar{\lambda}|a_j|
=
\frac{n}{m}
=
0.73958 \times 10.66667
=
7.88889
\]</span></p>
<p>Since the subregions are equal in size, we could simply calculate:</p>
<p><span class="math display">\[
e_j = \frac{71}{9} = 7.88889
\]</span></p>
<p>The chi-squared statistic is:</p>
<p><span class="math display">\[
\chi^2
=
\sum_{j=1}^{9}
\frac{(n_j-e_j)^2}{e_j}
\]</span></p>
<p>Using the observed quadrat counts:</p>
<p><span class="math display">\[
\begin{aligned}
\chi^2
={}&amp;
2 \times \frac{(8-7.89)^2}{7.89}
+
2 \times \frac{(6-7.89)^2}{7.89}
+
\frac{(7-7.89)^2}{7.89}
\\[4pt]
&amp;+
2 \times \frac{(11-7.89)^2}{7.89}
+
\frac{(9-7.89)^2}{7.89}
+
\frac{(5-7.89)^2}{7.89}
\\[4pt]
={}&amp;
\frac{36.89}{7.89}
=
4.676
\end{aligned}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>tS <span class="ot">&lt;-</span> <span class="fu">quadrat.test</span>(swp, <span class="dv">3</span>,<span class="dv">3</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(swp)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tS, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">cex=</span><span class="fl">1.5</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here -0.32 is the Pearson residual obtained with the formula:</p>
<p><span class="math display">\[
r_j =\frac{n_j-e_j}{\sqrt{e_j}}
\]</span> Large positive residuals indicate more points than expected, while large negative residuals indicate fewer points than expected.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>tS <span class="ot">&lt;-</span> <span class="fu">quadrat.test</span>(swp, <span class="dv">3</span>,<span class="dv">3</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>tS</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test of CSR using quadrat counts

data:  swp
X2 = 4.6761, df = 8, p-value = 0.4169
alternative hypothesis: two.sided

Quadrats: 3 by 3 grid of tiles</code></pre>
</div>
</div>
<p>Decision???</p>
<p>Inspecting the p-value, we see that the test does not reject the null hypothesis of CSR for the Swedish Pines data.</p>
<p>A few things to consider?</p>
</section>
<section id="some-issues-with-quadrat-methods" class="level2">
<h2 class="anchored" data-anchor-id="some-issues-with-quadrat-methods">Some issues with Quadrat Methods</h2>
<p>Effect of Quadrat Size:</p>
<p><img src="quadratcount.png" class="img-fluid"></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to learn more about quadrat size
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<section id="choice-of-quadrat-size." class="level3 callout-body-container callout-body">
<h3 class="anchored" data-anchor-id="choice-of-quadrat-size.">Choice of quadrat size.</h3>
<p>A key limitation of quadrat counting is that the number and size of quadrats are chosen arbitrarily. When the null hypothesis is rejected, the test only indicates that the observed point pattern is inconsistent with a homogeneous Poisson process. However, it does not reveal the reason for the departure. The pattern may exhibit spatially varying intensity (inhomogeneity), dependence between points (such as clustering or inhibition), or a combination of both. Consequently, the test provides little insight into the specific nature of the deviation from the null hypothesis.</p>
<p>The choice of quadrat size is therefore important. Quadrats should be large enough to capture meaningful spatial variation, but not so large that local patterns are averaged out. As illustrated in the figure, using very large quadrats may mask existing spatial patterns, causing the test to fail to detect departures from complete spatial randomness. Conversely, if quadrats are too small, many will contain only zero or one event, resulting in little variation among counts and reducing the power of the test.</p>
<p>In practice, it is common to repeat the analysis using several quadrat sizes to determine whether patterns emerge at different spatial scales. This sensitivity to the choice of zoning and scale means that quadrat counting is affected by the Modifiable Areal Unit Problem (MAUP). The next section introduces kernel density estimation, a density-based approach that is generally less sensitive to MAUP and provides a more flexible way to explore spatial point patterns.</p>
</section>
</div>
</div>
</section>
<section id="global-vs-local-measures" class="level2">
<h2 class="anchored" data-anchor-id="global-vs-local-measures">Global vs Local Measures</h2>
<ul>
<li>Global statistics: Intensity</li>
<li>Local statistics: Quadrat intensity</li>
</ul>
</section>
</section>
<section id="inhomogeneous-poisson-process-ipp" class="level1">
<h1>Inhomogeneous Poisson Process (IPP)</h1>
<p>In many real-world applications, assuming that a point process is <strong>homogeneous</strong> is unrealistic. For example, the spatial distribution of a city’s population is influenced by factors such as housing type, land use, neighbourhood characteristics, and accessibility. Similarly, the locations of trees in a forest depend on environmental conditions, including soil quality, moisture, elevation, slope, and sunlight. These factors cause the density of events to vary across space.</p>
<p>The <strong>Inhomogeneous Poisson Process (IPP)</strong> generalises the <strong>Homogeneous Poisson Process (HPP)</strong> by allowing the intensity to vary spatially. The assumption that events occur independently is retained, but the event rate is no longer constant. Instead, the intensity is represented by the spatially varying function</p>
<p><span class="math display">\[
\lambda(\mathbf{x}),
\]</span></p>
<p>which gives the expected number of events per unit area at location <span class="math inline">\(\mathbf{x}\)</span>. Regions with higher values of <span class="math inline">\(\lambda(\mathbf{x})\)</span> are more likely to contain events than regions with lower values, reflecting the underlying spatial heterogeneity.</p>
<hr>
<section id="estimation-of-intensity-for-ipp" class="level2">
<h2 class="anchored" data-anchor-id="estimation-of-intensity-for-ipp">Estimation of Intensity for IPP</h2>
<p>The intensity function of an <strong>Inhomogeneous Poisson Process (IPP)</strong> can be estimated using either <strong>non-parametric</strong> or <strong>parametric</strong> methods.</p>
<ul>
<li><p><strong>Non-parametric estimation</strong> makes minimal assumptions about the underlying intensity function and estimates it directly from the observed point pattern. A common approach is <strong>kernel smoothing</strong>, which produces a smooth estimate of the spatial intensity surface.</p></li>
<li><p><strong>Parametric estimation</strong> assumes that the intensity follows a specified functional form,</p>
<p><span class="math display">\[
\lambda(\mathbf{x}; \boldsymbol{\theta}),
\]</span></p>
<p>where <span class="math inline">\(\boldsymbol{\theta}\)</span> is a vector of unknown parameters. These parameters are typically estimated by <strong>maximum likelihood</strong>, yielding the intensity function that best explains the observed point pattern under the assumed model.</p></li>
</ul>
<hr>
</section>
<section id="estimating-the-intensity-of-an-ipp-kernel-smoothing" class="level2">
<h2 class="anchored" data-anchor-id="estimating-the-intensity-of-an-ipp-kernel-smoothing">Estimating the Intensity of an IPP: Kernel Smoothing</h2>
<p>A widely used <strong>non-parametric</strong> estimator of the intensity function is the <strong>kernel smoothing estimator</strong>:</p>
<p><span class="math display">\[
\hat{\lambda}(\mathbf{x})
=
\frac{1}{h^2}
\sum_{i=1}^{n}
\frac{
k\!\left(\dfrac{\|\mathbf{x}-\mathbf{x}_i\|}{h}\right)
}{
q(\mathbf{x})
},
\]</span></p>
<p>where:</p>
<ul>
<li><p><span class="math inline">\(k(\cdot)\)</span> is a <strong>bivariate, symmetric kernel function</strong>, such as the <strong>uniform</strong>, <strong>Epanechnikov (parabolic)</strong>, <strong>biweight (quartic)</strong>, or <strong>Gaussian</strong> kernel.</p></li>
<li><p><span class="math inline">\(\mathbf{x}_1,\mathbf{x}_2,\ldots,\mathbf{x}_n\)</span> are the observed event locations.</p></li>
<li><p><span class="math inline">\(h&gt;0\)</span> is the <strong>bandwidth</strong>, which controls the amount of smoothing:</p>
<ul>
<li>Small values of <span class="math inline">\(h\)</span> produce a highly detailed (peaky) intensity estimate that may capture random noise.</li>
<li>Large values of <span class="math inline">\(h\)</span> produce a smoother intensity surface, but may hide important local features.</li>
</ul></li>
<li><p><span class="math inline">\(q(\mathbf{x})\)</span> is the <strong>border correction factor</strong>.</p></li>
</ul>
<section id="border-correction" class="level3">
<h3 class="anchored" data-anchor-id="border-correction">Border correction</h3>
<p>Near the boundary of the study region, part of the kernel extends outside the observation window, where no data have been observed. As a result, points close to the edge receive less kernel weight than points in the interior, causing the estimated intensity to be <strong>biased downwards</strong> near the borders.</p>
<p>The border correction factor <span class="math inline">\(q(\mathbf{x})\)</span> compensates for this loss of kernel mass by rescaling the kernel contribution according to the proportion of the kernel that lies inside the study region. Consequently, locations near the boundary are not systematically underestimated.</p>
<p>Without border correction, the estimated intensity often appears artificially lower around the edges of the study area, even when the underlying process is homogeneous.</p>
</section>
<section id="kernel-density-for-csr-with-different-bandwidths" class="level3">
<h3 class="anchored" data-anchor-id="kernel-density-for-csr-with-different-bandwidths">Kernel Density for CSR with different Bandwidths</h3>
<section id="csr" class="level4">
<h4 class="anchored" data-anchor-id="csr">CSR</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">135</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>xy_csr <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">runif</span>(<span class="dv">80</span>), <span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>pp_csr <span class="ot">&lt;-</span> <span class="fu">as.ppp</span>(xy_csr, <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pp_csr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/xy_csr-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="regular" class="level4">
<h4 class="anchored" data-anchor-id="regular">Regular</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>regular <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"C:/Users/01438475/OneDrive - University of Cape Town/ASDA/regular.csv"</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>xy_regular <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">cbind</span>(regular<span class="sc">$</span>X,regular<span class="sc">$</span>Y), <span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>pp_regular <span class="ot">&lt;-</span> <span class="fu">as.ppp</span>(xy_regular, <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pp_regular)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="cluster-data-points" class="level4">
<h4 class="anchored" data-anchor-id="cluster-data-points">Cluster Data Points</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>cluster <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"C:/Users/01438475/OneDrive - University of Cape Town/ASDA/cluster.csv"</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>xy_cluster <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">cbind</span>(cluster<span class="sc">$</span>X,cluster<span class="sc">$</span>Y), <span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>pp_cluster <span class="ot">&lt;-</span> <span class="fu">as.ppp</span>(xy_cluster, <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pp_cluster)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="sigma-0.1" class="level5">
<h5 class="anchored" data-anchor-id="sigma-0.1">sigma = 0.1</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>den <span class="ot">&lt;-</span> <span class="fu">density</span>(pp_csr, <span class="at">sigma =</span> .<span class="dv">1</span>) <span class="co"># here you can specify a different kernel and a bandwidth</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(den, <span class="at">main =</span> <span class="st">"CSR"</span>) </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pp_csr, <span class="at">add=</span><span class="cn">TRUE</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">contour</span>(den, <span class="at">add=</span><span class="cn">TRUE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sigma-0.2" class="level5">
<h5 class="anchored" data-anchor-id="sigma-0.2">sigma = 0.2</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>den <span class="ot">&lt;-</span> <span class="fu">density</span>(pp_csr, <span class="at">sigma =</span> .<span class="dv">2</span>) <span class="co"># here you can specify a different kernel and a bandwidth</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(den, <span class="at">main =</span> <span class="st">"CSR"</span>) </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pp_csr, <span class="at">add=</span><span class="cn">TRUE</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">contour</span>(den, <span class="at">add=</span><span class="cn">TRUE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sigma-0.3" class="level5">
<h5 class="anchored" data-anchor-id="sigma-0.3">sigma = 0.3</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>den <span class="ot">&lt;-</span> <span class="fu">density</span>(pp_csr, <span class="at">sigma =</span> .<span class="dv">3</span>) <span class="co"># here you can specify a different kernel and a bandwidth</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(den, <span class="at">main =</span> <span class="st">"CSR"</span>) </span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pp_csr, <span class="at">add=</span><span class="cn">TRUE</span>)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="fu">contour</span>(den, <span class="at">add=</span><span class="cn">TRUE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If you don’t specify a sigma, bandwidth, R spatstat default is to take sigma equal to one-eighth of the shortest side length of the enclosing rectangle. This is a very rough rule of thumb which may be unsatisfactory in many cases.</p>
<p>Several algorithms are available for automatically selecting the bandwidth sigma by minimising a measure of error. They include bw.diggle for Diggle and Berman’s [222, 89] mean square error cross-validation method and bw.ppl for the likelihood cross-validation method [428, Sect. 5.3]. If you type bw. In R you will see there are many other bandwidth calculation methods.</p>
<p>There are many other things that we could talk about but we are not going to touch: Weighted Kernel estimators Spatially adaptive smoothing etc.</p>
</section>
</section>
</section>
</section>
<section id="kernel-density-in-existence-of-a-covariate" class="level2">
<h2 class="anchored" data-anchor-id="kernel-density-in-existence-of-a-covariate">Kernel density in existence of a covariate</h2>
<ul>
<li><p>Often we want to know how the intensity of points depends on the values of a covariate.</p></li>
<li><p>For example, it is of interest to determine whether the trees prefer steep or flat terrain, and whether they prefer a particular altitude.</p></li>
<li><p>Other applications include spatial epidemiology (e.g., disease risk as a function of environmental exposure), the density of clinics in CT can be adjusted by the population in CT. spatial ecology (e.g., habitat preferences of organisms),</p></li>
<li><p>Animal sightings might be due to a water point, or dense tree areas exploration geology (e.g., prospectivity of mineral deposits predicted from survey data), and seismology.</p></li>
<li><p>In this case we could adjust our kernel density by the covariate.</p></li>
<li><p>For example, the density of a disease occurrence can be adjusted by the population etc.</p></li>
</ul>
<section id="kernel-density-in-existence-of-a-covariate-1" class="level3">
<h3 class="anchored" data-anchor-id="kernel-density-in-existence-of-a-covariate-1">Kernel density in existence of a covariate</h3>
<ul>
<li>Investigating dependence of intensity on a covariate
<ul>
<li>Quadrats determined by a covariate</li>
<li>Relative distribution estimate</li>
<li>Distance map</li>
</ul></li>
</ul>
<p>Tests of dependence on a covariate Hotspots, clusters and local features Kernel smoothing of marks</p>
</section>
</section>
<section id="spatial-covariates" class="level2">
<h2 class="anchored" data-anchor-id="spatial-covariates">Spatial Covariates</h2>
<p>A <strong>spatial covariate</strong> is a variable whose value depends on spatial location. It can be represented as a function</p>
<p><span class="math display">\[
Z(\mathbf{u}),
\]</span></p>
<p>where <span class="math inline">\(\mathbf{u}\)</span> denotes a location in the study region.</p>
<p>Examples of spatial covariates include:</p>
<ul>
<li>Geographical coordinates (e.g., longitude and latitude)</li>
<li>Terrain elevation</li>
<li>Soil pH</li>
<li>Soil moisture</li>
<li>Land cover or vegetation type</li>
<li>Distance from a location <span class="math inline">\(\mathbf{u}\)</span> to another spatial feature (e.g., a road, river, coastline, or city centre)</li>
</ul>
<p>Spatial covariates may also be derived from other spatial datasets, such as:</p>
<ul>
<li>Another <strong>point pattern</strong> (e.g., distance to the nearest hospital or school)</li>
<li>A <strong>line pattern</strong> (e.g., roads or rivers)</li>
<li>An <strong>areal dataset</strong> (e.g., census regions or land-use polygons)</li>
<li>A <strong>continuous raster surface</strong> (e.g., elevation or temperature)</li>
</ul>
<p>For an inhomogeneous point process, the primary objective is often to determine whether the <strong>intensity</strong> of the point pattern depends on one or more spatial covariates. This relationship can be expressed as</p>
<p><span class="math display">\[
\lambda(\mathbf{u}) = f\big(Z(\mathbf{u})\big),
\]</span></p>
<p>or, more generally,</p>
<p><span class="math display">\[
\lambda(\mathbf{u})
=
f\left(
Z_1(\mathbf{u}),
Z_2(\mathbf{u}),
\ldots,
Z_p(\mathbf{u})
\right),
\]</span></p>
<p>where <span class="math inline">\(Z_1,\ldots,Z_p\)</span> are spatial covariates.</p>
<p>In practice, we typically <strong>model and account for the effects of spatial covariates before investigating dependence between points</strong>. This is because an apparent clustering pattern may simply reflect variation in environmental or geographical conditions rather than interaction between events.</p>
<section id="example-data-bei" class="level3">
<h3 class="anchored" data-anchor-id="example-data-bei">Example data: “bei”</h3>
<ul>
<li>The dataset bei gives the positions of 3605 trees of the species Beilschmiedia pendula(Lauraceae) in a 1000 by 500 metre rectangular sampling region in the tropical rainforest of Barro Colorado Island.</li>
<li>The accompanying datase bei.extragives information about the altitude (elevation) in the study region.</li>
<li>These data are part of a much larger dataset containing the positions of hundreds of thousands of trees belong to thousands of species.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>elev <span class="ot">&lt;-</span> bei.extra<span class="sc">$</span>elev </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(elev, <span class="at">main =</span> <span class="st">""</span>) </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bei, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">cex =</span> <span class="fl">0.3</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cols =</span> <span class="st">"white"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="investigating-the-effect-of-a-spatial-covariate" class="level2">
<h2 class="anchored" data-anchor-id="investigating-the-effect-of-a-spatial-covariate">Investigating the Effect of a Spatial Covariate</h2>
<section id="quadrat-counting-based-on-a-covariate" class="level3">
<h3 class="anchored" data-anchor-id="quadrat-counting-based-on-a-covariate">Quadrat Counting Based on a Covariate</h3>
<p>In quadrat counting, the study region can be partitioned into <strong>any collection of non-overlapping subregions</strong>. The quadrats do not have to be rectangular or have equal areas; they may be of any shape, provided they collectively cover the study region.</p>
<p>Rather than choosing quadrats arbitrarily, it is often more informative to define them using <strong>spatial covariate information</strong>. For example, if elevation is believed to influence the occurrence of events, the study region can be divided into zones of similar elevation.</p>
<p>Suppose the study region is classified into four elevation categories:</p>
<ul>
<li>Low</li>
<li>Medium-Low</li>
<li>Medium-High</li>
<li>High</li>
</ul>
<p>Each category defines a quadrat, and the observed number of events within each elevation zone can be compared with the number expected under an appropriate model.</p>
<p>This approach allows us to investigate whether the <strong>intensity of the point process varies systematically with the covariate</strong>. For example, if trees are found predominantly in high-elevation regions, the observed counts in those quadrats will be larger than expected under a homogeneous Poisson process.</p>
<p>Because the quadrats are defined according to the covariate rather than by an arbitrary grid, the resulting analysis is often more meaningful and directly addresses the scientific question of interest.</p>
<blockquote class="blockquote">
<p><strong>Example:</strong> For the tropical rainforest dataset (<code>bei</code> in <strong>spatstat</strong>), the study region can be partitioned into elevation classes (Low, Medium-Low, Medium-High, and High). Quadrat counts can then be compared across these elevation zones to assess whether tree intensity depends on terrain elevation.</p>
</blockquote>
</section>
<section id="tropical-rain-forest-trees-dataset" class="level3">
<h3 class="anchored" data-anchor-id="tropical-rain-forest-trees-dataset">Tropical rain forest trees dataset</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"bei"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Assign the elevation covariate to a variable elev by typing</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>elev <span class="ot">&lt;-</span> bei.extra<span class="sc">$</span>elev</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Plot the trees on top of an image of the elevation covariate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(elev, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bei, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">cex =</span> <span class="fl">0.3</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cols =</span> <span class="st">"white"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For the tropical rainforest data bei, it might be useful to split the study region into several sub-regions according to the terrain elevation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">quantile</span>(elev, <span class="at">probs=</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">4</span>)<span class="sc">/</span><span class="dv">4</span>, <span class="at">type=</span><span class="dv">2</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>Zcut <span class="ot">&lt;-</span> <span class="fu">cut</span>(elev, <span class="at">breaks=</span>b, <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"Med-Low"</span>, <span class="st">"Med-High"</span>, <span class="st">"High"</span>))</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="fu">textureplot</span>(Zcut, <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Convert the image from above to a tesselation, count the number of points in each region using quadratcount, and plot the quadrat counts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>V <span class="ot">&lt;-</span> <span class="fu">tess</span>(<span class="at">image=</span>Zcut)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>qc <span class="ot">&lt;-</span> <span class="fu">quadratcount</span>(bei, <span class="at">tess =</span> V)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>qc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tile
     Low  Med-Low Med-High     High 
     714      883     1344      663 </code></pre>
</div>
</div>
<p>The output shows the number of trees in each region. Since the four regions have equal area, the counts should be approximately equal if there is a uniform density of trees. Obviously they are not equal; there appears to be a strong preference for higher elevations (dropping off for the highest elevations).</p>
<p>Estimate the intensity in each of the four regions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">intensity</span>(qc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tile
        Low     Med-Low    Med-High        High 
0.005623154 0.006960978 0.010593103 0.005228707 </code></pre>
</div>
</div>
<p>Assume that the intensity of trees is a function ((u) = (e(u))) where (e(u)) is the terrain elevation at location u.</p>
<p>Compute a nonparametric estimate of the function () and plot it by</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>rh <span class="ot">&lt;-</span> <span class="fu">rhohat</span>(bei, elev)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rh)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Compute the predicted intensity based on this estimate of ().</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>predictedrho <span class="ot">&lt;-</span> <span class="fu">predict</span>(rh)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(predictedrho, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bei, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">cols =</span> <span class="st">"white"</span>, <span class="at">cex =</span> .<span class="dv">2</span>, <span class="at">pch =</span> <span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Compute a non-parametric estimate by kernel smoothing and compare with the predicted intensity above.</p>
<p>The kernel density estimate of the points is computed and plotted with the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>kerneldensity <span class="ot">&lt;-</span> <span class="fu">density</span>(bei, <span class="at">sigma =</span> bw.scott)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kerneldensity, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kerneldensity, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">cols =</span> <span class="st">"white"</span>, <span class="at">cex =</span> .<span class="dv">2</span>, <span class="at">pch =</span> <span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Compare the two</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(predictedrho, kerneldensity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">eval.im</span>(kerneldensity<span class="sc">-</span>predictedrho))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-33-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Which seems to be quite different from the predicted intensity.</p>
<p>The difference of estimates at corresponding pixels can be plotted as an image using plot(eval.im(kden - pred)); the difference should be roughly equal to 0 everwhere.</p>
<p>For the Beilschmiedia data with terrain elevation as the covariate, these graphics suggest that (6.18) is a reasonable approximation.</p>
<p>By contrast, a similar exercise performed for the terrain slope covariate suggests that forest density is not simply a function of terrain slope.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>